# Imports

In [1]:
import pandas as pd
import numpy as np

# Preprocesamiento

In [2]:
animeList = pd.read_csv("Datos/anime_cleaned.csv")
userAnimeList = pd.read_csv("Datos/animelists_cleaned.csv")
userList = pd.read_csv("Datos/users_cleaned.csv")

In [3]:
animeList.head()

,anime_id,title,title_english,title_japanese,title_synonyms,image_url,type,source,episodes,status,...,broadcast,related,producer,licensor,studio,genre,opening_theme,ending_theme,duration_min,aired_from_year
0,11013,Inu x Boku SS,Inu X Boku Secret Service,妖狐×僕SS,Youko x Boku SS,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,12,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 17207, 'type': 'man...","Aniplex, Square Enix, Mainichi Broadcasting Sy...",Sentai Filmworks,David Production,"Comedy, Supernatural, Romance, Shounen","['""Nirvana"" by MUCC']","['#1: ""Nirvana"" by MUCC (eps 1, 11-12)', '#2: ...",24.0,2012.0
1,2104,Seto no Hanayome,My Bride is a Mermaid,瀬戸の花嫁,The Inland Sea Bride,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,26,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 759, 'type': 'manga...","TV Tokyo, AIC, Square Enix, Sotsu",Funimation,Gonzo,"Comedy, Parody, Romance, School, Shounen","['""Romantic summer"" by SUN&LUNAR']","['#1: ""Ashita e no Hikari (明日への光)"" by Asuka Hi...",24.0,2007.0
2,5262,Shugo Chara!! Doki,Shugo Chara!! Doki,しゅごキャラ！！どきっ,"Shugo Chara Ninenme, Shugo Chara! Second Year",https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,51,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 101, 'type': 'manga...","TV Tokyo, Sotsu",NaN,Satelight,"Comedy, Magic, School, Shoujo","['#1: ""Minna no Tamago (みんなのたまご)"" by Shugo Cha...","['#1: ""Rottara Rottara (ロッタラ ロッタラ)"" by Buono! ...",24.0,2008.0
3,721,Princess Tutu,Princess Tutu,プリンセスチュチュ,NaN,https://myanimelist.cdn-dena.com/images/anime/...,TV,Original,38,Finished Airing,...,Fridays at Unknown,"{'Adaptation': [{'mal_id': 1581, 'type': 'mang...","Memory-Tech, GANSIS, Marvelous AQL",ADV Films,Hal Film Maker,"Comedy, Drama, Magic, Romance, Fantasy","['""Morning Grace"" by Ritsuko Okazaki']","['""Watashi No Ai Wa Chiisaikeredo"" by Ritsuko ...",16.0,2002.0
4,12365,Bakuman. 3rd Season,Bakuman.,バクマン。,Bakuman Season 3,https://myanimelist.cdn-dena.com/images/anime/...,TV,Manga,25,Finished Airing,...,Unknown,"{'Adaptation': [{'mal_id': 9711, 'type': 'mang...","NHK, Shueisha",NaN,J.C.Staff,"Comedy, Drama, Romance, Shounen","['#1: ""Moshimo no Hanashi (もしもの話)"" by nano.RIP...","['#1: ""Pride on Everyday"" by Sphere (eps 1-13)...",24.0,2012.0

In [4]:
userAnimeList.head()

,username,anime_id,my_watched_episodes,my_start_date,my_finish_date,my_score,my_status,my_rewatching,my_rewatching_ep,my_last_updated,my_tags
0,karthiga,21,586,0000-00-00,0000-00-00,9,1,NaN,0,2013-03-03 10:52:53,NaN
1,karthiga,59,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-10 13:54:51,NaN
2,karthiga,74,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-04-27 16:43:35,NaN
3,karthiga,120,26,0000-00-00,0000-00-00,7,2,NaN,0,2013-03-03 10:53:57,NaN
4,karthiga,178,26,0000-00-00,0000-00-00,7,2,0.0,0,2013-03-27 15:59:13,NaN

In [5]:
userList.head()

,username,user_id,user_watching,user_completed,user_onhold,user_dropped,user_plantowatch,user_days_spent_watching,gender,location,birth_date,access_rank,join_date,last_online,stats_mean_score,stats_rewatched,stats_episodes
0,karthiga,2255153,3,49,1,0,0,55.091667,Female,"Chennai, India",1990-04-29 00:00:00,NaN,2013-03-03 00:00:00,2014-02-04 01:32:00,7.43,0.0,3391
1,Damonashu,37326,45,195,27,25,59,82.574306,Male,"Detroit,Michigan",1991-08-01 00:00:00,NaN,2008-02-13 00:00:00,2017-07-10 06:52:54,6.15,6.0,4903
2,bskai,228342,25,414,2,5,11,159.483333,Male,"Nayarit, Mexico",1990-12-14 00:00:00,NaN,2009-08-31 00:00:00,2014-05-12 16:35:00,8.27,1.0,9701
3,terune_uzumaki,327311,5,5,0,0,0,11.394444,Female,"Malaysia, Kuantan",1998-08-24 00:00:00,NaN,2010-05-10 00:00:00,2012-10-18 19:06:00,9.70,6.0,697
4,Bas_G,5015094,35,114,6,20,175,30.458333,Male,"Nijmegen, Nederland",1999-10-24 00:00:00,NaN,2015-11-26 00:00:00,2018-05-10 20:53:37,7.86,0.0,1847

### Anime List

Notemos que esta lista tiene las siguientes columnas

In [6]:
animeList.columns

Index(['anime_id', 'title', 'title_english', 'title_japanese',
       'title_synonyms', 'image_url', 'type', 'source', 'episodes', 'status',
       'airing', 'aired_string', 'aired', 'duration', 'rating', 'score',
       'scored_by', 'rank', 'popularity', 'members', 'favorites', 'background',
       'premiered', 'broadcast', 'related', 'producer', 'licensor', 'studio',
       'genre', 'opening_theme', 'ending_theme', 'duration_min',
       'aired_from_year'],
      dtype='object')

Eliminemos las columnas que no entregan información o no son relevantes para nuestros objetivos

En primer lugar notemos que tenemos cuatro columnas para titulo 

- title
- title_english
- title_japanese
- title_synonyms

Por esto solo vamos a quedarnos con el valor de "title".

En segundo lugar "image_url" es un link para la imagen promocional del anime, por tanto se decide eliminarlo.

En tercer lugar "status" y "airing" entregan la misma información "status" tiene dos valores "Finished Airing" y "Currently Airing" mientras que "airing" representa lo mismo con "True" y "False", por tanto vamos a elminiar "status".

En cuarto lugar tenemos las columnas "aired_string" y "aired" que indican las fechas entre los cuales ha sido emitido el anime. La segunda esta representada como un diccionario mientras que la primera es un texto. Por tanto nos quedaremos con la segunda.

En el siguiente lugar esta "duration" y "duration_min" que entregan el tiempo de duración por episodio, "duration" lo hace con forma de string, mientras que "duration_min" como entero. Por esto se va a borrar la columna "duration".

A continuación se encuentra "background", esta columna informa detalles sobre cada anime. Solo se tienen 813 valores con información de 6668 (es decir un 12\% ) de la información luego se decidio eliminar esta columna.

La siguiente columna es "premiered" la cual dice cuando se estreno el anime, esta columna tiene 3702 valores NAN por lo tanto se decide ignorarla, pero aun asi no se pierde información pues existe la columna "aired_from_year" que indica el año de estreno del anime (cabe destacar esta ultima columna no tiene valores NAN)

La columna "boradcast" indica los dias en que el anime era emitido, también se decide eliminar la columna pues tiene 3688 valores NAN.

La columna "producer" indica los productores asociados al anime, se tiene que hay 2266 valores NAN y por tanto se decide eliminar.

Al igual que las ultimas columnas la columna "licensor" tiene un alto valor de NAN (3881) por tanto se decide eliminar.

Por ultimo se decide eliminar las columnas "opening_theme" y "ending_theme" pues no se cree que generen información relevante para el estudio.

In [7]:
animeList = animeList.drop(columns=['title_english','title_japanese','title_synonyms',
                                   'image_url',
                                    'status',
                                    'aired_string',
                                    'duration',
                                    'background',
                                    'premiered',
                                    'broadcast',
                                    'producer',
                                    'licensor'])

Las columnas acutalmente presentes en animeList son:

In [12]:
animeList.columns

Index(['anime_id', 'title', 'type', 'source', 'episodes', 'airing', 'aired',
       'rating', 'score', 'scored_by', 'rank', 'popularity', 'members',
       'favorites', 'related', 'studio', 'genre', 'opening_theme',
       'ending_theme', 'duration_min', 'aired_from_year'],
      dtype='object')

In [9]:
animeList['genre'].isnull().values.any()

True

In [10]:
animeList['genre'].isnull().values.sum()

4

In [11]:
animeList['genre'].unique()

array(['Comedy, Supernatural, Romance, Shounen',
       'Comedy, Parody, Romance, School, Shounen',
       'Comedy, Magic, School, Shoujo', ..., 'Romance, School, Sports',
       'Action, Adventure, Demons, Fantasy, Magic',
       'Horror, Parody, Supernatural'], dtype=object)